apiVersion: v1
kind: Secret
metadata:
  name: content-platform-secret
  namespace: content-platform
type: Opaque
stringData:
  AZURE_STORAGE_CONNECTION_STRING: "REMPLACER_PAR_LA_VRAIE_CONNECTION_STRING"